### ISSUE TITLE
set suitable default value for process, source and task config items

### ISSUE THREAD

**Issue by csuzhangxc** [pingcap/dm#1130]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

we do not set a suitable value for some config items (like `statement-size`, this may dump too large txn to make TiDB OOM)

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM v2.0.0-rc.2
        ```

**Comment by csuzhangxc** [comment]
dumpling has set the default value of `statement-size` in https://github.com/pingcap/dumpling/pull/160

**Comment by lance6716** [comment]
some default config which maybe dangerous

use dumpling default value: 
- if `mydumper` in config is not null but lack some items:
  - `FileSize` is `UnspecifiedSize`, but seems one big file could have multiple insert statements, will check if it's fine
  - `Rows` is `UnspecifiedSize`, don't split table every `Rows` into multiple files, seems fine because we didn't set it before
  - `SessionParams` is empty, maybe we could make use of it in future
  - `DumpEmptyDatabase`, `NoViews`

overwrite dumpling to DM specified default:
- `EscapeBackslash` is true (what's this)

[WIP]
